export const MARKETPLACE_ADDRESS = 
  (`${process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS}`)
export const NFT_DROP_ADDRESS = 
  (`${process.env.NEXT_PUBLIC_NFT_DROP_ADDRESS}`)
export const NFT_COLLECTION_ADDRESS = 
  (`${process.env.NEXT_PUBLIC_NFT_COLLECTION_ADDRESS}`)
